### ISSUE TITLE
May the version of transformers in Dependencies be wrong?

### ISSUE THREAD

**Issue by Zebulon-Chen** [Eleanor-H/DAGN#2]
The dependency `transformers` name `pytorch_transformers` before version 2.0, [refer this](https://github.com/huggingface/transformers/tags?after=v2.4.1)
I tried `transformers==4.5.1`  which is the latest release and I got error as follows:

```
Traceback (most recent call last):
  File "run_multiple_choice.py", line 464, in <module>
    main()
  File "run_multiple_choice.py", line 403, in main
    model_path=model_args.model_name_or_path if os.path.isdir(model_args.model_name_or_path) else None
  File "/home/zhchen/.conda/envs/dagn2/lib/python3.7/site-packages/transformers/trainer.py", line 927, in train
    self.model = self.model.from_pretrained(resume_from_checkpoint)
  File "/home/zhchen/.conda/envs/dagn2/lib/python3.7/site-packages/transformers/modeling_utils.py", line 1059, in from_pretrained
    model = cls(config, *model_args, **model_kwargs)
TypeError: __init__() missing 3 required positional arguments: 'init_weights', 'max_rel_id', and 'hidden_size'
```

**Comment by Eleanor-H** [comment]
Hi, this could be the version. Maybe you should try a lower one.

**Comment by Zebulon-Chen** [comment]
> 
> 
> Hi, this could be the version. Maybe you should try a lower one.

Thank you for your reply.

Actually, I have tried 1.2.0 released in [here](https://github.com/huggingface/transformers/releases/tag/1.2.0), and I could not find version 1.3.0 in either [github](https://github.com/huggingface/transformers/tags?after=v2.4.1) or [pypi](https://pypi.org/project/transformers/#history).

As I mentioned above, the `transformers` before version 2.0 is named `pytorch_transformers`. Here is what I got when running in `transformers==1.2.0`
```
Traceback (most recent call last):
  File "run_multiple_choice.py", line 27, in <module>
    from transformers import (
ModuleNotFoundError: No module named 'transformers'
```

**Comment by Zebulon-Chen** [comment]
well, 3.3.0 can work, thank you very much.

**Comment by Eleanor-H** [comment]
Yes it should be transformers==3.1.0 in the main page. I have corrected the typo. My apologies and thank you for the reminder!
