### ISSUE TITLE
How to run baseline?

### ISSUE THREAD

**Issue by starry-y** [Eleanor-H/DAGN#3]
Hello, I want to know how to run baseline.

 if I should set `use_pool = True & use_gcn = False`? Other settings are fix ?

If yes, why the code is killed by itself?

**Comment by Eleanor-H** [comment]
Hi, a simpler way to run baselines is [here](https://github.com/yuweihao/reclor).

**Comment by starry-y** [comment]
How about LogiQA dataset?

The values are not the ones in the original paper.

**Comment by Eleanor-H** [comment]
You can write a processor for LogiQA dataset like [this](https://github.com/yuweihao/reclor/blob/master/utils_multiple_choice.py).

**Comment by starry-y** [comment]
There is a LogiQAProcessor in your utils_multiple_choice.py.
 Can I use it ?
Or could you tell me where I should modify？

**Comment by Eleanor-H** [comment]
Yes you can use it.

**Comment by starry-y** [comment]
Should I delete three ids and two masks?

**Comment by starry-y** [comment]
I used you code, but it is killed when I trained baseline model.

**Comment by Eleanor-H** [comment]
My code is not the exact baseline and it is just for some convenient debugging. The LogiQA baseline results are obtained by running [this](https://github.com/yuweihao/reclor) with [a LogiQA processor](https://github.com/Eleanor-H/DAGN/blob/main/utils_multiple_choice.py#L257) without the three ids.

**Comment by Eleanor-H** [comment]
You can use [this](https://github.com/yuweihao/reclor/blob/master/utils_multiple_choice.py#L341) to convert the features.

**Comment by starry-y** [comment]
Thank you very much !!!

**Comment by starry-y** [comment]
I tried again, but failed.
I have another question that in run_multiple_choice.py, if use_gcn is False, what optimizer should I give to baseline model?

**Comment by Eleanor-H** [comment]
[The default optimizer](https://huggingface.co/docs/transformers/main_classes/optimizer_schedules#transformers.AdamW).

**Comment by starry-y** [comment]
ok, thanks

**Comment by starry-y** [comment]
Hello, could you share your baseline file?
I've tried all of the methods I could, but it doesn't work. 
Thank you very much!

**Comment by Eleanor-H** [comment]
I have updated this repo. Please check it.

**Comment by starry-y** [comment]
Thanks a lot !


发自我的iPhone

------------------ Original ------------------
From: Yinya Huang ***@***.***&gt;
Date: 周二,1月 11,2022 10:53
To: Eleanor-H/DAGN ***@***.***&gt;
Cc: starry-y ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [Eleanor-H/DAGN] How to run baseline? (Issue #3)





 
I have updated this repo. Please check it.
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
